default['my_rbenv']['user']            = 'rbenv'
default['my_rbenv']['group']           = 'rbenv'
default['my_rbenv']['version']         = '2.1.5'
default['my_rbenv']['my_rbenv_url']    = 'https://github.com/sstephenson/rbenv.git'
default['my_rbenv']['ruby-build_url']  = 'https://github.com/sstephenson/ruby-build.git'
default['my_rbenv']['rbenv-default-gems']  = 'https://github.com/sstephenson/rbenv-default-gems.git'
